# Drawing helpers on top of framebuf: proportional fonts, icons, sparklines.
# Font and icon bitmaps are read from assets.bin as they are drawn, one glyph
# at a time, since the ESP8266 can't spare the RAM to hold them all (assets.py
# says where each glyph is; both generated by tools/make_assets.py).
import framebuf

import assets

_HLSB = framebuf.MONO_HLSB
_file = open("assets.bin", "rb")
_buf = bytearray(assets.MAX_GLYPH_BYTES)
_view = memoryview(_buf)

# Palette for drawing black glyphs onto white: source 1 -> 0, source 0 -> 1 (=key).
_INVERT = framebuf.FrameBuffer(bytearray(1), 2, 1, _HLSB)
_INVERT.pixel(0, 0, 1)


def _load(offset, w, h):
    size = (w + 7) // 8 * h
    _file.seek(offset)
    _file.readinto(_view[:size])
    return framebuf.FrameBuffer(_view[:size], w, h, _HLSB)


def _blit(fb, glyph, x, y, c):
    if c:
        fb.blit(glyph, x, y, 0)
    else:
        fb.blit(glyph, x, y, 1, _INVERT)


def text_width(font, s):
    chars, widths = font[1], font[2]
    total = 0
    for ch in s:
        i = chars.find(ch)
        if i >= 0:
            total += widths[i]
    return total


def text(fb, font, s, x, y, c=1):
    """Draw s with its top-left corner at (x, y); returns the x after the last glyph."""
    height, chars, widths, offsets = font
    for ch in s:
        i = chars.find(ch)
        if i >= 0:
            w = widths[i]
            _blit(fb, _load(offsets[2 * i] | offsets[2 * i + 1] << 8, w, height), x, y, c)
            x += w
    return x


def text_center(fb, font, s, y, c=1, x0=0, x1=128):
    return text(fb, font, s, x0 + (x1 - x0 - text_width(font, s)) // 2, y, c)


def text_right(fb, font, s, x_right, y, c=1):
    return text(fb, font, s, x_right - text_width(font, s), y, c)


def icon(fb, ic, x, y, c=1):
    w, h, offset = ic
    _blit(fb, _load(offset, w, h), x, y, c)
    return x + w


def dotted_hline(fb, x, y, w, c=1):
    for i in range(x, x + w, 2):
        fb.pixel(i, y, c)


def sparkline(fb, values, x, y, w, h, min_span):
    """Line chart of the values (oldest first, None = gap), newest at the right edge.

    The vertical scale fits the data but never spans less than min_span, so a
    steady reading draws a calm line instead of amplified noise. Below the line
    a sparse dot pattern gives the area some body.
    """
    points = [v for v in values if v is not None]
    if len(points) < 2:
        dotted_hline(fb, x, y + h - 1, w)
        return
    lo, hi = min(points), max(points)
    if hi - lo < min_span:
        mid = (hi + lo) / 2
        lo, hi = mid - min_span / 2, mid + min_span / 2
    n = len(values)
    step = w / (n - 1) if n > 1 else w
    bottom = y + h - 1
    prev = None
    for i, v in enumerate(values):
        if v is None:
            prev = None
            continue
        px = x + int(i * step + 0.5)
        py = bottom - int((v - lo) * (h - 1) / (hi - lo) + 0.5)
        if prev:
            fb.line(prev[0], prev[1], px, py, 1)
            # Fill under the segment with every 3rd column, every 2nd pixel.
            for fx in range(prev[0], px + 1):
                if fx % 3 == 0:
                    top = prev[1] + (py - prev[1]) * (fx - prev[0]) // max(1, px - prev[0])
                    for fy in range(top + 2, bottom + 1, 2):
                        fb.pixel(fx, fy, 1)
        prev = (px, py)
    fb.hline(x, bottom, w, 1)
